Repository SensoryPeople/SensoryPeople, pull requests merged in 2024-07, with the labels that each got.

#7 ♻️ refactor - #6 상태코드 int ->HttpStatus 변경
  src/main/java/com/sparta/sensorypeople/common/DataCommonResponse.java
  src/main/java/com/sparta/sensorypeople/common/StatusCommonResponse.java
  src/main/java/com/sparta/sensorypeople/common/exception/ErrorCode.java
Labels: ♻️ refactor

#9 feat : 보드 CRUD 기본 구현.
  src/main/java/com/sparta/sensorypeople/domain/board/controller/BoardController.java
  src/main/java/com/sparta/sensorypeople/domain/board/dto/BoardRequestDto.java
  src/main/java/com/sparta/sensorypeople/domain/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/Board.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/BoardMember.java
  src/main/java/com/sparta/sensorypeople/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
  src/main/resources/application.yml
Labels: 🌟 feat

#13 🔥feat - BoardMember entity 관련 기능 구현 (추후 BoardController/Service로 이전 리…
  src/main/java/com/sparta/sensorypeople/common/exception/ErrorCode.java
  src/main/java/com/sparta/sensorypeople/domain/board/controller/BoardController.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/BoardMember.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/BoardRoleEnum.java
  src/main/java/com/sparta/sensorypeople/domain/board/repository/BoardMemberRepository.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardMemberService.java
  src/main/java/com/sparta/sensorypeople/domain/user/repository/UserRepository.java
Labels: 🌟 feat

#15 🔥feat - #2 Card, BoardMember 기능 구현 및 전체 기능 통합
  build.gradle
  http/user.http
  src/main/java/com/sparta/sensorypeople/common/TimeStamp.java
  src/main/java/com/sparta/sensorypeople/common/exception/ErrorCode.java
  src/main/java/com/sparta/sensorypeople/domain/board/controller/BoardController.java
  src/main/java/com/sparta/sensorypeople/domain/board/dto/MemberRequestDto.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/Board.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/BoardMember.java
  src/main/java/com/sparta/sensorypeople/domain/board/repository/BoardMemberRepository.java
  src/main/java/com/sparta/sensorypeople/domain/board/repository/BoardRepository.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardMemberService.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
  src/main/java/com/sparta/sensorypeople/domain/card/controller/CardController.java
  src/main/java/com/sparta/sensorypeople/domain/card/dto/CardRequestDto.java
  src/main/java/com/sparta/sensorypeople/domain/card/dto/CardResponseDto.java
  src/main/java/com/sparta/sensorypeople/domain/card/entity/Card.java
  src/main/java/com/sparta/sensorypeople/domain/card/repository/CardRepository.java
  src/main/java/com/sparta/sensorypeople/domain/card/service/CardService.java
  src/main/java/com/sparta/sensorypeople/domain/column/controller/ColumnController.java
  src/main/java/com/sparta/sensorypeople/domain/column/entity/Columns.java
  src/main/java/com/sparta/sensorypeople/domain/column/repository/ColumnRepository.java
  src/main/java/com/sparta/sensorypeople/domain/column/service/ColumnService.java
  src/main/java/com/sparta/sensorypeople/domain/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/sensorypeople/security/filter/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: 🌟 feat, ♻️ refactor

#17 ✨ update - 카드 드래그앤 드롭 구현
  src/main/java/com/sparta/sensorypeople/domain/card/controller/CardController.java
  src/main/java/com/sparta/sensorypeople/domain/card/entity/Card.java
  src/main/java/com/sparta/sensorypeople/domain/card/repository/CardRepository.java
  src/main/java/com/sparta/sensorypeople/domain/card/service/CardService.java
Labels: 🌟 feat

#21 Feat/#5 board Controller, Service 간 비즈니스 로직 분리.
  src/main/java/com/sparta/sensorypeople/domain/board/controller/BoardController.java
  src/main/java/com/sparta/sensorypeople/domain/board/entity/Board.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
  src/main/java/com/sparta/sensorypeople/domain/user/repository/UserRepository.java
Labels: 🌟 feat, ♻️ refactor

#23 🔥feat - front 초기세팅
  src/main/front/.gitignore
  src/main/front/README.md
  src/main/front/package-lock.json
  src/main/front/package.json
  src/main/front/public/favicon.ico
  src/main/front/public/index.html
  src/main/front/public/logo192.png
  src/main/front/public/logo512.png
  src/main/front/public/manifest.json
  src/main/front/public/robots.txt
  src/main/front/src/App.css
  src/main/front/src/App.js
  src/main/front/src/App.test.js
  src/main/front/src/MainPage.css
  src/main/front/src/MainPage.js
  src/main/front/src/components/BoardList.css
  src/main/front/src/components/BoardList.js
  src/main/front/src/components/LoginForm.css
  src/main/front/src/components/LoginForm.js
  src/main/front/src/components/SignUpForm.css
  src/main/front/src/components/SignUpForm.js
  src/main/front/src/index.css
  src/main/front/src/index.js
  src/main/front/src/logo.svg
  src/main/front/src/reportWebVitals.js
  src/main/front/src/setupTests.js
Labels: 🌟 feat

#24 Feat/#22 comment
  http/user.http
  src/main/java/com/sparta/sensorypeople/common/exception/ErrorCode.java
  src/main/java/com/sparta/sensorypeople/domain/board/controller/BoardController.java
  src/main/java/com/sparta/sensorypeople/domain/board/repository/BoardMemberRepository.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardMemberService.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
  src/main/java/com/sparta/sensorypeople/domain/card/controller/CardController.java
  src/main/java/com/sparta/sensorypeople/domain/card/entity/Card.java
  src/main/java/com/sparta/sensorypeople/domain/card/service/CardService.java
  src/main/java/com/sparta/sensorypeople/domain/column/service/ColumnService.java
  src/main/java/com/sparta/sensorypeople/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/sensorypeople/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/sensorypeople/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/sensorypeople/domain/comment/entity/Comment.java
  src/main/java/com/sparta/sensorypeople/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/sensorypeople/domain/comment/service/CommentService.java
  src/main/java/com/sparta/sensorypeople/domain/user/service/UserService.java
  src/main/java/com/sparta/sensorypeople/domain/user/service/UserServiceImpl.java
Labels: 🌟 feat, ♻️ refactor

#25 Feat/#22 comment
  src/main/java/com/sparta/sensorypeople/domain/board/entity/Board.java
  src/main/java/com/sparta/sensorypeople/domain/column/controller/ColumnController.java
  src/main/java/com/sparta/sensorypeople/domain/column/service/ColumnService.java
Labels: ♻️ refactor

#26 🔥feat - 컬럼, 보드멤버, 커멘트 디자인 추가
  src/main/front/package-lock.json
  src/main/front/package.json
  src/main/front/src/App.js
  src/main/front/src/components/BoardList.js
  src/main/front/src/components/BoardMember.css
  src/main/front/src/components/BoardMember.js
  src/main/front/src/components/CardComments.css
  src/main/front/src/components/CardComments.js
  src/main/front/src/components/Column.js
  src/main/front/src/components/KanbanBoard.css
  src/main/front/src/components/KanbanBoard.js
  src/main/front/src/components/LoginForm.js
  src/main/front/src/components/Task.js
Labels: 🌟 feat

#27 Feat/#3 front
  src/main/front/src/App.js
  src/main/front/src/components/BoardList.js
  src/main/front/src/components/BoardMember.js
  src/main/front/src/components/LoginForm.js
Labels: 🌟 feat

#28 ♻️ refactor - 초대 권한 확인 code 리팩토링
  src/main/java/com/sparta/sensorypeople/common/exception/ErrorCode.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
  src/main/java/com/sparta/sensorypeople/domain/card/controller/CardController.java
Labels: ♻️ refactor

#29 🔥feat - 보드멤버 조회 기능 (어드민)
  src/main/java/com/sparta/sensorypeople/domain/board/controller/BoardController.java
  src/main/java/com/sparta/sensorypeople/domain/board/dto/MemberRequestDto.java
  src/main/java/com/sparta/sensorypeople/domain/board/dto/MemberResponseDto.java
  src/main/java/com/sparta/sensorypeople/domain/board/repository/BoardMemberRepository.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
Labels: 🌟 feat

#30 🔥feat - 컬럼 조회 기능 구현
  src/main/java/com/sparta/sensorypeople/domain/column/controller/ColumnController.java
  src/main/java/com/sparta/sensorypeople/domain/column/repository/ColumnRepository.java
  src/main/java/com/sparta/sensorypeople/domain/column/service/ColumnService.java
Labels: 🌟 feat

#31 ♻️ refactor - create return 값 수정
  src/main/java/com/sparta/sensorypeople/domain/column/controller/ColumnController.java
  src/main/java/com/sparta/sensorypeople/domain/column/dto/ColumnRequestDto.java
  src/main/java/com/sparta/sensorypeople/domain/column/service/ColumnService.java
Labels: ♻️ refactor

#32 🔥feat - 보드멤버에서 칸반보드로 연결 및 생성 삭제 구현
  src/main/front/src/App.js
  src/main/front/src/components/BoardList.js
  src/main/front/src/components/BoardMember.js
  src/main/front/src/components/Column.js
  src/main/front/src/components/KanbanBoard.js
  src/main/front/src/components/Task.js
Labels: 🌟 feat

#33 ♻️ refactor - card query name -> id로 가져오도록 변경
  src/main/java/com/sparta/sensorypeople/domain/card/controller/CardController.java
  src/main/java/com/sparta/sensorypeople/domain/card/service/CardService.java
Labels: ♻️ refactor

#36 ♻️ refactor - 분산락 적용
  build.gradle
  src/main/java/com/sparta/sensorypeople/common/redisson/RedissonConfig.java
  src/main/java/com/sparta/sensorypeople/common/redisson/RedissonLock.java
  src/main/java/com/sparta/sensorypeople/common/redisson/RedissonLockAspect.java
  src/main/java/com/sparta/sensorypeople/domain/board/service/BoardService.java
  src/main/java/com/sparta/sensorypeople/domain/card/service/CardService.java
  src/main/java/com/sparta/sensorypeople/domain/column/controller/ColumnController.java
  src/main/java/com/sparta/sensorypeople/domain/column/service/ColumnService.java
  src/main/java/com/sparta/sensorypeople/domain/comment/service/CommentService.java
  src/main/java/com/sparta/sensorypeople/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/sensorypeople/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/sparta/sensorypeople/ColumnServiceTest.java
  src/test/java/com/sparta/sensorypeople/domain/user/service/concurrency_controll/UserServiceImplTest.java
Labels: ♻️ refactor

#38 ♻️ refactor - KanbanBoard.js - 카드생성시 즉시 조회되도록 변경
  src/main/front/src/components/AddCardForm.js
  src/main/front/src/components/KanbanBoard.js
Labels: ♻️ refactor
